![alt text](https://www.nlab.org.uk/wp-content/uploads/nlab.png)
# ML Practical 3: Evaluation of multiple models

## The task.

Task: Predict whether a person makes over $50k per year from census data known about them.

Data set from the paper: Kohavi, Ron. "Scaling up the accuracy of Naive-Bayes classifiers: a decision-tree hybrid." KDD. Vol. 96. 1996.
Data URL: We will be using modified versions of the publically avaliable data. Please download the data from the URLs provided.

**Output Feature:**

Feature | type | values
:-------:|:--------:|:--------:|
salary | categorical | >50K, <=50K|

**Input features**

|     Feature    |     Type    |                                                                                                                                                                                                              Values                                                                                                                                                                                                             |
|:--------------:|:-----------:|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|       age      |  continuous |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|    workclass   | categorical |                                                                                                                                                              Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked                                                                                                                                                              |
|     fnlwgt     |  continuous |                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|    education   | categorical |                                                                                                                                      Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.                                                                                                                                     |
|  education-num |  continuous |                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| marital-status | categorical |                                                                                                                                                            Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.                                                                                                                                                           |
|   occupation   | categorical |                                                                                                    Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.                                                                                                    |
|  relationship  | categorical |                                                                                                                                                                               Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.                                                                                                                                                                               |
|      race      | categorical |                                                                                                                                                                                   White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.                                                                                                                                                                                  |
|       sex      | categorical |                                                                                                                                                                                                          Female, Male.                                                                                                                                                                                                          |
|  capital-gain  |  continuous |                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|  capital-loss  |  continuous |                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| hours-per-week |  continuous |                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| native-country | categorical | United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands. |

# To help you along some of the basic data preparation has been done for you.
Read the code. Understand what has been done.

In [70]:
# Some basic imports
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, GridSearchCV

# Read the data into a pandas DataFrame
data = pd.read_csv('https://drive.google.com/uc?export=download&id=1lBiNrYBk5KdfBllyjuELgRwYaK4yT2z9', header = 0, names = ['age','workclass','fnlwgt','education','education-num','matrial-status','occupation','relationship','race','sex','captial-gain','captial-loss','hours-per-week','salary'])

In [71]:
data.head()

,age,workclass,fnlwgt,education,education-num,matrial-status,occupation,relationship,race,sex,captial-gain,captial-loss,hours-per-week,salary
0,25,Private,292058,HS-grad,9,Never-married,Other-service,Other-relative,White,Male,0,0,30,<=50K
1,28,Private,285294,Bachelors,13,Married-civ-spouse,Sales,Wife,Black,Female,15024,0,45,>50K
2,31,Private,113364,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,>50K
3,33,Federal-gov,29617,Some-college,10,Divorced,Other-service,Not-in-family,Black,Male,0,0,40,<=50K
4,34,Private,157289,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,<=50K

In [72]:
data.describe()

,age,fnlwgt,education-num,captial-gain,captial-loss,hours-per-week
count,3500.000000,3.500000e+03,3500.000000,3500.000000,3500.000000,3500.000000
mean,38.453714,1.869128e+05,10.181143,1121.488286,94.314286,40.262571
std,13.683679,1.054498e+05,2.408376,7554.172001,420.050908,12.326367
min,17.000000,1.930200e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.156482e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.753350e+05,10.000000,0.000000,0.000000,40.000000
75%,47.000000,2.334195e+05,12.250000,0.000000,0.000000,45.000000
max,90.000000,1.033222e+06,16.000000,99999.000000,3683.000000,99.000000

In [73]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             3500 non-null   int64
 1   workclass       3500 non-null   object
 2   fnlwgt          3500 non-null   int64
 3   education       3500 non-null   object
 4   education-num   3500 non-null   int64
 5   matrial-status  3500 non-null   object
 6   occupation      3500 non-null   object
 7   relationship    3500 non-null   object
 8   race            3500 non-null   object
 9   sex             3500 non-null   object
 10  captial-gain    3500 non-null   int64
 11  captial-loss    3500 non-null   int64
 12  hours-per-week  3500 non-null   int64
 13  salary          3500 non-null   object
dtypes: int64(6), object(8)
memory usage: 382.9+ KB

In [74]:
# Define our input features and our output feature
# Call our input features X and our output feature y (the sklearn standard)
# Note that we have categorical features.
X = data.drop( columns = 'salary' )
y = data.salary

In [75]:
# Now we need to encode our output feature to be an integer 0 or 1.
# This is because we have a binary classification problem and in order to use sklearn's
# built-in evaluation measures we need to have one class defined as 1 (target) and one as 0 (non-target).

# We could do this by using the LabelEncoder from sklearn. The LabelEncoder will convert n-distinct values
# to 0,..,n-1 values in this case giving us what we want. We assume that our training set contains both
# labels and that this mapping will be valid. However, we have no control
# over which value is represented by 1 and which is represented by 0.
# Therefore it is easier (in terms of subsequent interpretation) to do this
# manually. Recall the problem, we want our target variable (1) to be '>50k'

# To do this (your variable y is a pandas.Series object, use the replace method):
# 1) update all values '<=50K' within y to equal 0
# 2) update all values '>50K' within y to equal 1

y.replace(to_replace = ' <=50K', value = 0, inplace = True)
y.replace(to_replace = ' >50K', value = 1, inplace = True)

/var/folders/kf/5c3rzd1n3mg01xt7v99dzfvr0000gn/T/ipykernel_17694/2113570133.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y.replace(to_replace = ' >50K', value = 1, inplace = True)

In [76]:
# The baseline classifier for you to use
lr_model = Pipeline([
    ('onehot',OneHotEncoder(handle_unknown='ignore',sparse_output = False)),  # will automatically pick string columns (could have specified)
    ('standardize', StandardScaler()), # will convert everything (can't specify which columns but all columns are fine after onehot)
    ('model',LogisticRegression(solver = 'liblinear') )
    ])

# Your turn. See the instructions in the slide deck...

In [77]:
# Initial split
X_train, X_test, y_train, y_test = train_test_split( X, y, random_state = 42)

In [78]:
# Model list



# The baseline classifier for you to use

rf1 = Pipeline([
    ('onehot',OneHotEncoder(handle_unknown='ignore',sparse_output = False)),  # will automatically pick string columns (could have specified)
    ('model',RandomForestClassifier(n_estimators = 100, max_depth=100, max_features = 'sqrt', criterion='gini') )
    ])

rf2 = Pipeline([
    ('onehot',OneHotEncoder(handle_unknown='ignore',sparse_output = False)),  # will automatically pick string columns (could have specified)
    ('model',RandomForestClassifier(n_estimators = 100, max_depth=100, max_features = 'log2', criterion='gini') )
    ])

rf3 = Pipeline([
    ('onehot',OneHotEncoder(handle_unknown='ignore',sparse_output = False)),  # will automatically pick string columns (could have specified)
    ('model',RandomForestClassifier(n_estimators = 100, max_depth=200, criterion='gini') )
    ])

model_list = [rf1,rf2,rf3]

In [79]:

from collections import defaultdict
results = defaultdict(list)

# For each model further split and do the evaluation
for model in model_list:
    # Define the further data split we'll use
    for i in range(5):
        X_train_sub, X_valid, y_train_sub, y_valid = train_test_split( X_train, y_train, random_state = i)

        # Train and test with this split
        model.fit(X_train_sub, y_train_sub)
        s = model.score(X_valid, y_valid)
        # Store the result
        results[f'model: {i}'].append(s)

print(results)

defaultdict(<class 'list'>, {'model: 0': [0.8432267884322678, 0.8188736681887366, 0.832572298325723], 'model: 1': [0.8158295281582952, 0.806697108066971, 0.8097412480974124], 'model: 2': [0.8203957382039574, 0.8127853881278538, 0.817351598173516], 'model: 3': [0.817351598173516, 0.8051750380517504, 0.8143074581430746], 'model: 4': [0.817351598173516, 0.8188736681887366, 0.8143074581430746]})

In [80]:
# Get the best model
final_model = Pipeline([
    ('onehot',OneHotEncoder(handle_unknown='ignore',sparse_output = False)),  # will automatically pick string columns (could have specified)
    ('model',RandomForestClassifier(n_estimators = 100, max_depth=100, max_features = 'sqrt', criterion='gini') )
    ])

In [81]:
# Train and test with the final split
final_model.fit(X_train,y_train)
final_model.score(X_test,y_test)

0.8571428571428571

In [82]:
# Train deployment version

# TASK 1: Train a basic model and evaluate it on the test set.

In [83]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    stratify=y,
    random_state=42
)

print("Training size:", X_train.shape)
print("Test size:", X_test.shape)

Training size: (2450, 13)
Test size: (1050, 13)

In [84]:
X_subtrain, X_valid, y_subtrain, y_valid = train_test_split(
    X_train, y_train,
    test_size=0.3,
    stratify=y_train,
    random_state=42
)

print("Subtrain size:", X_subtrain.shape)
print("Validation size:", X_valid.shape)

Subtrain size: (1715, 13)
Validation size: (735, 13)

In [85]:
n_estimators_list = [50, 100]
max_depth_list = [None, 20]
max_features_list = ['sqrt', None]

In [86]:
best_score = 0
best_model = None
best_params = None

for n in n_estimators_list:
    for depth in max_depth_list:
        for feature in max_features_list:
            
            model = Pipeline([
                ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
                ('rf', RandomForestClassifier(
                    n_estimators=n,
                    max_depth=depth,
                    max_features=feature,
                    random_state=42
                ))
            ])
            
            # Train
            model.fit(X_subtrain, y_subtrain)
            
            # Validate
            score = model.score(X_valid, y_valid)
            
            print("Trees:", n,
                  "Depth:", depth,
                  "Max_features:", feature,
                  "Validation Accuracy:", score)
            
            if score > best_score:
                best_score = score
                best_model = model
                best_params = (n, depth, feature)

print("\nBest Validation Score:", best_score)
print("Best Parameters:", best_params)

Trees: 50 Depth: None Max_features: sqrt Validation Accuracy: 0.8244897959183674
Trees: 50 Depth: None Max_features: None Validation Accuracy: 0.8408163265306122
Trees: 50 Depth: 20 Max_features: sqrt Validation Accuracy: 0.8258503401360544
Trees: 50 Depth: 20 Max_features: None Validation Accuracy: 0.8353741496598639
Trees: 100 Depth: None Max_features: sqrt Validation Accuracy: 0.8312925170068027
Trees: 100 Depth: None Max_features: None Validation Accuracy: 0.8408163265306122
Trees: 100 Depth: 20 Max_features: sqrt Validation Accuracy: 0.8217687074829932
Trees: 100 Depth: 20 Max_features: None Validation Accuracy: 0.8353741496598639

Best Validation Score: 0.8408163265306122
Best Parameters: (50, None, None)

In [87]:
if best_model is not None:
    best_model.fit(X_train, y_train)
    test_accuracy = best_model.score(X_test, y_test)
    print("Final Test Accuracy:", test_accuracy)
else:
    print("No best model found.")

Final Test Accuracy: 0.8419047619047619

In [88]:
if best_model is not None:
    deploy_model = best_model.fit(X, y)
    print("Model trained on full dataset and ready for deployment.")
else:
    print("No best model found.")

Model trained on full dataset and ready for deployment.

# TASK 2: Perform hyperparameter tuning using GridSearchCV and evaluate the best model on the test set.

## Task 2a: Compare multiple models using cross-validation

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

models = {
    "lr_baseline": LogisticRegression(solver="liblinear", random_state=42),
    "rf1": RandomForestClassifier(max_depth=100, random_state=42, n_jobs=-1),
    "rf2": RandomForestClassifier(max_depth=10, random_state=42, n_jobs=-1),
    "svc1": SVC(C=1.0, kernel="rbf"),
    "svc2": SVC(C=10.0, kernel="rbf"),
    "svc3": SVC(C=1.0, kernel="linear"),
    "svc4": SVC(C=10.0, kernel="linear")
}

kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

results = {}
pipelines = {}

for name, model in models.items():
    pipeline = Pipeline([
        ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
        ("scaler", StandardScaler()),
        ("model", model)
    ])
    
    cv_scores = cross_val_score(pipeline, X_train, y_train, cv=kf, n_jobs=-1)

    results[name] = cv_scores.mean()
    pipelines[name] = pipeline

print("Validation average scores:")
for name, score in results.items():
    print(f"{name}: {score}")


# best_model = pipelines[max(results, key=results.get)]
best_name = max(results, key=lambda k: results[k])
best_model = pipelines[best_name]

best_model.fit(X_train, y_train)

print("Best model:", best_model)
print("Test score:", best_model.score(X_test, y_test))


best_model.fit(X, y)

Validation average scores:
lr_baseline: 0.8209604388587352
rf1: 0.8270803703596202
rf2: 0.7836197138130206
svc1: 0.8316314979827591
svc2: 0.8213377644907556
svc3: 0.7874147389196877
svc4: 0.7874147389196877
Best model: Pipeline(steps=[('encoder',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
                ('scaler', StandardScaler()), ('model', SVC())])
Test score: 0.8582857142857143

Pipeline(steps=[('encoder',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
                ('scaler', StandardScaler()), ('model', SVC())])

## Task 2b: GridSearchCV for RandomForest hyperparameter tuning

In [90]:

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

param_grid = {
    "model__max_depth": [5, 10, 100],
    "model__max_features": ["sqrt", "log2"]
}
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

pipeline = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
    ("scaler", StandardScaler()),
    ("model", RandomForestClassifier(random_state=42, n_jobs=-1))
])

meta_estimator = GridSearchCV(pipeline, param_grid, cv=kf, n_jobs=-1)
meta_estimator.fit(X_train, y_train)

print("Best validation average score:")
print(meta_estimator.best_score_)

best_model = meta_estimator.best_estimator_
print("Best model:", best_model)

print("Test score:", best_model.score(X_test, y_test))

best_model.fit(X, y)

Best validation average score:
0.8270803703596202
Best model: Pipeline(steps=[('encoder',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
                ('scaler', StandardScaler()),
                ('model',
                 RandomForestClassifier(max_depth=100, n_jobs=-1,
                                        random_state=42))])
Test score: 0.8514285714285714

Pipeline(steps=[('encoder',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
                ('scaler', StandardScaler()),
                ('model',
                 RandomForestClassifier(max_depth=100, n_jobs=-1,
                                        random_state=42))])

# Task 3: Perform hyperparameter tuning using RandomizedSearchCV and evaluate the best model on the test set.

In [91]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    stratify=y,
    random_state=42
)

In [92]:

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 2450
Testing samples: 1050

In [93]:
from typing import Literal

rf_n_estimators = [50, 100, 200]
rf_max_depth = [None, 10, 20]
rf_max_features = ['sqrt', 'log2']
rf_max_features: list[Literal['sqrt', 'log2']] = ['sqrt', 'log2']
rf_min_samples_split = [2, 5]

In [94]:
# Manual Tuning for Random Forest
best_rf_score = 0
best_rf_model = None
best_rf_params = None

for n in rf_n_estimators:
    for depth in rf_max_depth:
        for features in rf_max_features:
            for min_split in rf_min_samples_split:
                
                model = Pipeline([
                    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
                    ('scaler', StandardScaler()),
                    ('rf', RandomForestClassifier(
                        n_estimators=n,
                        max_depth=depth,
                        max_features=features,
                        min_samples_split=min_split,
                        random_state=42,
                        n_jobs=-1
                    ))
                ])
                
                model.fit(X_train, y_train)
                score = model.score(X_test, y_test)
                
                print("RF -> n:", n,
                      "depth:", depth,
                      "features:", features,
                      "min_split:", min_split,
                      "Test Acc:", round(score, 4))
                
                if score > best_rf_score:
                    best_rf_score = score
                    best_rf_model = model
                    best_rf_params = (n, depth, features, min_split)

print("\nBest RF Score:", best_rf_score)
print("Best RF Params:", best_rf_params)

RF -> n: 50 depth: None features: sqrt min_split: 2 Test Acc: 0.8295
RF -> n: 50 depth: None features: sqrt min_split: 5 Test Acc: 0.8343
RF -> n: 50 depth: None features: log2 min_split: 2 Test Acc: 0.8248
RF -> n: 50 depth: None features: log2 min_split: 5 Test Acc: 0.8276
RF -> n: 50 depth: 10 features: sqrt min_split: 2 Test Acc: 0.7829
RF -> n: 50 depth: 10 features: sqrt min_split: 5 Test Acc: 0.7829
RF -> n: 50 depth: 10 features: log2 min_split: 2 Test Acc: 0.7543
RF -> n: 50 depth: 10 features: log2 min_split: 5 Test Acc: 0.7543
RF -> n: 50 depth: 20 features: sqrt min_split: 2 Test Acc: 0.8286
RF -> n: 50 depth: 20 features: sqrt min_split: 5 Test Acc: 0.8295
RF -> n: 50 depth: 20 features: log2 min_split: 2 Test Acc: 0.76
RF -> n: 50 depth: 20 features: log2 min_split: 5 Test Acc: 0.7581
RF -> n: 100 depth: None features: sqrt min_split: 2 Test Acc: 0.8276
RF -> n: 100 depth: None features: sqrt min_split: 5 Test Acc: 0.8381
RF -> n: 100 depth: None features: log2 min_split: 2 Test Acc: 0.8295
RF -> n: 100 depth: None features: log2 min_split: 5 Test Acc: 0.8295
RF -> n: 100 depth: 10 features: sqrt min_split: 2 Test Acc: 0.7838
RF -> n: 100 depth: 10 features: sqrt min_split: 5 Test Acc: 0.7876
RF -> n: 100 depth: 10 features: log2 min_split: 2 Test Acc: 0.7543
RF -> n: 100 depth: 10 features: log2 min_split: 5 Test Acc: 0.7543
RF -> n: 100 depth: 20 features: sqrt min_split: 2 Test Acc: 0.8238
RF -> n: 100 depth: 20 features: sqrt min_split: 5 Test Acc: 0.8248
RF -> n: 100 depth: 20 features: log2 min_split: 2 Test Acc: 0.7552
RF -> n: 100 depth: 20 features: log2 min_split: 5 Test Acc: 0.7571
RF -> n: 200 depth: None features: sqrt min_split: 2 Test Acc: 0.8295
RF -> n: 200 depth: None features: sqrt min_split: 5 Test Acc: 0.8324
RF -> n: 200 depth: None features: log2 min_split: 2 Test Acc: 0.8333
RF -> n: 200 depth: None features: log2 min_split: 5 Test Acc: 0.8305
RF -> n: 200 depth: 10 features: sqrt min_split: 2 Test Acc: 0.7857
RF -> n: 200 depth: 10 features: sqrt min_split: 5 Test Acc: 0.7867
RF -> n: 200 depth: 10 features: log2 min_split: 2 Test Acc: 0.7543
RF -> n: 200 depth: 10 features: log2 min_split: 5 Test Acc: 0.7543
RF -> n: 200 depth: 20 features: sqrt min_split: 2 Test Acc: 0.8229
RF -> n: 200 depth: 20 features: sqrt min_split: 5 Test Acc: 0.821
RF -> n: 200 depth: 20 features: log2 min_split: 2 Test Acc: 0.7552
RF -> n: 200 depth: 20 features: log2 min_split: 5 Test Acc: 0.7562

Best RF Score: 0.8380952380952381
Best RF Params: (100, None, 'sqrt', 5)

In [95]:
# SVM Hyperparameters
svm_C = [0.1, 1, 10]
svm_kernel: list[Literal['linear', 'rbf']] = ['linear', 'rbf']
svm_gamma: list[Literal['scale', 'auto']] = ['scale', 'auto']

In [96]:
# Manual Tuning for SVM
best_svm_score = 0
best_svm_model = None
best_svm_params = None

for C in svm_C:
    for kernel in svm_kernel:
        for gamma in svm_gamma:
            
            model = Pipeline([
                ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
                ('scaler', StandardScaler()),
                ('svm', SVC(
                    C=C,
                    kernel=kernel,
                    gamma=gamma,
                    random_state=42
                ))
            ])
            
            model.fit(X_train, y_train)
            score = model.score(X_test, y_test)
            
            print("SVM -> C:", C,
                  "kernel:", kernel,
                  "gamma:", gamma,
                  "Test Acc:", round(score, 4))
            
            if score > best_svm_score:
                best_svm_score = score
                best_svm_model = model
                best_svm_params = (C, kernel, gamma)

print("\nBest SVM Score:", best_svm_score)
print("Best SVM Params:", best_svm_params)

SVM -> C: 0.1 kernel: linear gamma: scale Test Acc: 0.8057
SVM -> C: 0.1 kernel: linear gamma: auto Test Acc: 0.8057
SVM -> C: 0.1 kernel: rbf gamma: scale Test Acc: 0.7543
SVM -> C: 0.1 kernel: rbf gamma: auto Test Acc: 0.7543
SVM -> C: 1 kernel: linear gamma: scale Test Acc: 0.8048
SVM -> C: 1 kernel: linear gamma: auto Test Acc: 0.8048
SVM -> C: 1 kernel: rbf gamma: scale Test Acc: 0.8467
SVM -> C: 1 kernel: rbf gamma: auto Test Acc: 0.8467
SVM -> C: 10 kernel: linear gamma: scale Test Acc: 0.8048
SVM -> C: 10 kernel: linear gamma: auto Test Acc: 0.8048
SVM -> C: 10 kernel: rbf gamma: scale Test Acc: 0.8457
SVM -> C: 10 kernel: rbf gamma: auto Test Acc: 0.8457

Best SVM Score: 0.8466666666666667
Best SVM Params: (1, 'rbf', 'scale')

In [97]:
if best_rf_score >= best_svm_score:
    best_model = best_rf_model
    best_score = best_rf_score
    print("Overall Best Model: Random Forest")
else:
    best_model = best_svm_model
    best_score = best_svm_score
    print("Overall Best Model: SVM")

print("Final Test Accuracy:", round(best_score, 4))

Overall Best Model: SVM
Final Test Accuracy: 0.8467

In [98]:
if best_model is not None:
    best_model.fit(X, y)
    print("Model trained on full dataset and ready for deployment.")
else:
    print("No best model found.")

Model trained on full dataset and ready for deployment.