<img src="https://www.nlab.org.uk/wp-content/uploads/nlabmain.png" style="width:40%; clear:both; margin-bottom:-20px" align=left>
<br style="clear:both;"/>

## Analytics Specializations & Applications - Week 8

# Recommender systems
----------
Dr Georgiana Nica-Avram - University of Nottingham
[mail](mailto:georgiana.nica-avram1@nottingham.ac.uk)
[web](http://www.neodemographics.org)

Increasingly, organisations gather much personal data through the application of digital technology and then use it to develop **personalised communication**, with the aim of making the content appear more aligned to an individual's interests. This helps organisations reap the benefits of brand loyalty given that they better understood their customers' needs, preferences, and even their disposable budget.

Personalised shopping experiences is something that all companies are currently interested (including Capital One, Pets at Home, and even Boots). Recommender systems can be used to personalize everything from the content of websites tailord to each visitor, to deriving better product recommendations for customers, and their use has snowballed since the inception of web. In this session we will get a firm ground in their underpinnings.

## Scenario:
This week we consider the method behind a working recommendation system that is able to 1) take in user ratings data about products and to 2) return us recommendations about what new items a customer might like that they simply haven't tried before. We'll use the example of Music store, which has ratings from its customers about some of their prior purchases.


### Task 1a: Getting some customer ratings into the system
As ever we need some information to underpin our decision making. Just to break from the norm, let's just consider that we have been provided with a python dictionary full of data. This dictionary is keyed by a particular person's name, and contains information about how they have rated each product.

<span style="font-weight:bold; color:green;">&rarr; run the following code to load the product ratings up into memory, and check you have some information for 10 customers:<span/>

In [1]:
customers = {
     "Andrew": {
         "Tame Impala": 5.0,
         "Broken Bells": 2.0,
         "Adele": 3.0,
         "Radiohead": 5.0,
         "Tenacious D": 4.0,
         "The Strokes": 5.0
     },
     "Gavin": {
        "Tame Impala": 2.0,
        "Broken Bells": 3.5,
        "Skrillex": 4.0,
        "Radiohead": 2.0,
        "Tenacious D": 3.5,
        "Vampire Weekend": 3.0
     },
     "Georgiana": {
        "Tame Impala": 3.5,
        "Broken Bells": 2.0,
        "Adele": 4.5,
        "Radiohead": 5.0,
        "Tenacious D": 1.5,
        "The Strokes": 2.5,
        "Vampire Weekend": 2.0
     },
     "Chan": {
         "Tame Impala": 5.0,
         "Broken Bells": 1.0,
         "Skrillex": 1.0,
         "Adele": 3.0,
         "Radiohead": 5,
         "Tenacious D": 1.0},
     "Dan": {
         "Tame Impala": 3.0,
         "Broken Bells": 4.0,
         "Skrillex": 4.5,
         "Radiohead": 3.0,
         "Tenacious D": 4.5,
         "The Strokes": 4.0,
         "Vampire Weekend": 2.0
     },
     "Valerie": {
         "Broken Bells": 4.0,
         "Skrillex": 1.0,
         "Adele": 4.0,
         "The Strokes": 4.0,
         "Vampire Weekend": 1.0
     },
     "Gregor": {
         "Broken Bells": 4.5,
         "Skrillex": 4.0,
         "Adele": 5.0,
         "Radiohead": 5.0,
         "Tenacious D": 4.5,
         "The Strokes": 4.0,
         "Vampire Weekend": 4.0
     },
     "Veronica": {
         "Tame Impala": 3.0,
         "Adele": 5.0,
         "Radiohead": 4.0,
         "Tenacious D": 2.5,
         "The Strokes": 3.0
          },
     "Clara": {
         "Tame Impala": 4.75,
         "Adele": 4.5,
         "Radiohead": 5.0,
         "The Strokes": 4.25,
         "Jay-Z": 4
    },
     "Robert": {
         "Tame Impala": 4.0,
         "Adele": 3.0,
         "Radiohead": 5.0,
         "The Strokes": 2.0,
         "Jay-Z": 1.0
     }
}

print("Our python dictionary has data for {} people in it.".format(len(customers)))

Our python dictionary has data for 10 people in it.

<span style="font-weight:bold; color:green;">&rarr; Print out the data for Veronica to check your customer data is loaded in correctly:<span/>

In [2]:
print(customers["Veronica"])

{'Tame Impala': 3.0, 'Adele': 5.0, 'Radiohead': 4.0, 'Tenacious D': 2.5, 'The Strokes': 3.0}

Veronica appears to be a big Adele fan.

### Task 1b: Taking a peek at the customer ratings
While python dictionaries are fine, we've got used to being able to manipulate data in pandas. It's very easy to convert into that format, so let's do that below, and have a look at our customer ratings in a nicely-formatted table.

<span style="font-weight:bold; color:green;">&rarr; run the following code to create a pandas DataFrame representation:<span/>

In [3]:
import pandas
data = pandas.DataFrame.from_dict(customers, orient="index")
data

,Tame Impala,Broken Bells,Adele,Radiohead,Tenacious D,The Strokes,Skrillex,Vampire Weekend,Jay-Z
Andrew,5.00,2.0,3.0,5.0,4.0,5.00,NaN,NaN,NaN
Gavin,2.00,3.5,NaN,2.0,3.5,NaN,4.0,3.0,NaN
Georgiana,3.50,2.0,4.5,5.0,1.5,2.50,NaN,2.0,NaN
Chan,5.00,1.0,3.0,5.0,1.0,NaN,1.0,NaN,NaN
Dan,3.00,4.0,NaN,3.0,4.5,4.00,4.5,2.0,NaN
Veronica,3.00,NaN,5.0,4.0,2.5,3.00,NaN,NaN,NaN
Clara,4.75,NaN,4.5,5.0,NaN,4.25,NaN,NaN,4.0
Robert,4.00,NaN,3.0,5.0,NaN,2.00,NaN,NaN,1.0
Valerie,NaN,4.0,4.0,NaN,NaN,4.00,1.0,1.0,NaN
Gregor,NaN,4.5,5.0,5.0,4.5,4.00,4.0,4.0,NaN

There are two things worthy of note here:
1. Pandas used every artist name it saw and generated a colum for it - if a customer hadn't rated a particular artist then a NaN flag ("Not a Number") was put in instead.
2. While our data doesn't actually have a field for a customer's name, pandas has used that information for the 'index' of the table. This is a bit like a row number, but in a label format.

We can list these labels as follows:

In [4]:
data.index

Index(['Andrew', 'Gavin', 'Georgiana', 'Chan', 'Dan', 'Veronica', 'Clara',
       'Robert', 'Valerie', 'Gregor'],
      dtype='object')

Having an index for each row can be very useful - for example, to get at an individual user's rating we can use the **loc[]** command and their index, such as:

In [5]:
data.loc['Andrew']

Tame Impala        5.0
Broken Bells       2.0
Adele              3.0
Radiohead          5.0
Tenacious D        4.0
The Strokes        5.0
Skrillex           NaN
Vampire Weekend    NaN
Jay-Z              NaN
Name: Andrew, dtype: float64

<span style="font-weight:bold; color:green;">&rarr; print out the data for "Gavin":<span/>

In [6]:
print(data.loc['Gavin'])

Tame Impala        2.0
Broken Bells       3.5
Adele              NaN
Radiohead          2.0
Tenacious D        3.5
The Strokes        NaN
Skrillex           4.0
Vampire Weekend    3.0
Jay-Z              NaN
Name: Gavin, dtype: float64

### Task 1c: Finding which customers are similar to each other
At the heart of any recommendation system, is finding similarities between either products (item-based recommendation) or customers (user-based recommendation). Let's focus on customers - what does it mean to say that two customers are similar (and hence one customer's purchases might be good recommendations for another?).

We could ignore rating values and start by looking at the sets of rated bands.

<span style="font-weight:bold; color:green;">&rarr; Let's use the code below to calculate the size of their commonly rated bands and divide it by the size of the union of the two sets of ratings, which is the Jaccard similarity coefficient:<span/>

In [7]:
intersection = set(data.loc['Gavin']).intersection(set(data.loc['Andrew']))
union = set(data.loc['Gavin']).union(set(data.loc['Andrew']))
jaccard_similarity = len(intersection) / len(union)
print(jaccard_similarity)

0.2727272727272727

The Jaccard similarity does not address the fact that Andrew and Gavin might have rated the same bands differently. So cmmonalities between their ratings seems like a good next step. Pandas again makes it easy to do this:

<span style="font-weight:bold; color:green;">&rarr; Consider the code below that finds the difference between two customers:<span/>

In [8]:
data.loc['Gavin'] - data.loc['Andrew']

Tame Impala       -3.0
Broken Bells       1.5
Adele              NaN
Radiohead         -3.0
Tenacious D       -0.5
The Strokes        NaN
Skrillex           NaN
Vampire Weekend    NaN
Jay-Z              NaN
dtype: float64

What have we done here? We've actually taken one vector (Gavin's) and deducted another (Andrew's) from it. Hopefully this use of vectors to represent information will remind you of our text analytics week.

What happens if we make these differences absolute (positive) and add them together? This corresponds to the Manhattan distance!

<span style="font-weight:bold; color:green;">&rarr; Adjust the previous difference calculation by wrapping the result in np.abs()</span>

In [9]:
import numpy as np

difference = np.sum(data.loc['Gavin'] - data.loc['Andrew'])
print(difference)

-5.0

<span style="font-weight:bold; color:green;">&rarr; Find the difference between Andrew and Gavin's preferences by taking the difference calculated above and using np.sum()</span>

In [10]:
distance = np.sqrt(np.sum((data.loc['Gavin'] - data.loc['Andrew']) ** 2))
print("Andrew and Gavin are {} apart.".format(distance))

Andrew and Gavin are 4.527692569068709 apart.

As we don't want to type in all of the above every time we want to compare two customers, let's create a function that will speed things up for us:

<span style="font-weight:bold; color:green;">&rarr; examine the following code, and make sure you understand what it is doing:</span>

In [11]:
def manhattan_distance(user1, user2):
    difference = np.abs(user1 - user2)
    distance = np.sum(difference)
    return distance

manhattan_distance(data.loc['Andrew'], data.loc['Gavin'])

np.float64(8.0)

Of course we know this is only one option - we could have created a Euclidian version too.

<span style="font-weight:bold; color:green;">&rarr; OPTIONAL CHALLENGE - create a version of the above function, that calculates the Euclidian distance between two customers</span>

In [12]:
def euclidian_distance(user1, user2):
    #-- square the differences between each user's rating
    squared_differences = (user1 - user2) ** 2

    #-- add the squared differences together
    sum_squared_differences = np.sum(squared_differences)

    #-- and return the square root of that sum!
    sqrt_result = np.sqrt(sum_squared_differences)
    return sqrt_result

#-- test out the result by looking at the euclidian distance
#-- between customers Andrew and Gavin
euclidian_distance(data.loc['Andrew'], data.loc['Gavin'])

np.float64(4.527692569068709)

### Task 1d: A flaw in our thinking?
There is a subtle issue here that is occurring - the fact that some people don't have a rating at all means that it is just not included in our calculations. Let's quickly explore what this means.

<span style="font-weight:bold; color:green;">&rarr; Use pen and paper to work out the Manhattan distance between Valeria and Veronica</span>

In [13]:
data.loc[['Valerie','Veronica']]

,Tame Impala,Broken Bells,Adele,Radiohead,Tenacious D,The Strokes,Skrillex,Vampire Weekend,Jay-Z
Valerie,NaN,4.0,4.0,NaN,NaN,4.0,1.0,1.0,NaN
Veronica,3.0,NaN,5.0,4.0,2.5,3.0,NaN,NaN,NaN

What result did you get? Notice that you just had to ignore any field that didn't have a rating for both customer's. How does this compare to the distance between Andrew and Gavin?

<span style="font-weight:bold; color:green;">&rarr; Use pen and paper to work out the manhattan distance between Andrew and Gavin</span>

In [14]:
data.loc[['Andrew','Gavin']]

,Tame Impala,Broken Bells,Adele,Radiohead,Tenacious D,The Strokes,Skrillex,Vampire Weekend,Jay-Z
Andrew,5.0,2.0,3.0,5.0,4.0,5.0,NaN,NaN,NaN
Gavin,2.0,3.5,NaN,2.0,3.5,NaN,4.0,3.0,NaN

Who are closest - Andrew and Gavin, or Valerie and Veronica?

We have found a potential flaw here which occurs when calculating distance measures with real world data that contains missing values.

When we compute the distance between Valerie and Veronica, they only had two artists in common (Adele and The Strokes), whereas Gavin and Andrew had multiple artists in common. This means that Gavin and Andrew are going to have a higher manhattan distance as we are working it out in more dimensions. This seems to skew our distance measurements.

Manhattan distance and euclidean distance work best when there are no missing values. Dealing with missing values is an active area of research, and in a bit we will talk about how to deal with this problem. For now just be aware of the flaw as we continue our first exploration into building a recommendation platform.

### Task 1e: Finding the distances between all customers
At this point in your studies, you should be able to create a table that lists the distances between each customer.

To safe time, please examine the following code I've created for you to do just this:

In [15]:
user_distances = {}

#-- loop through all of the customers
for i in data.index:
    distances = {}

    #-- for the current customer loop through the others
    for j in data.index:

        #-- if they are different people calculate and store their distance
        if i != j:
            distances[j] = manhattan_distance(data.loc[i],data.loc[j])
        #-- otherwise just add a "not-a-number" in the results table
        else:
            distances[j] = np.nan

    #-- add the current customers differences to our final results
    user_distances[i] = distances

#-- cast the results as a pandas dataframe
user_distances = pandas.DataFrame.from_dict(user_distances, orient="index")
user_distances

,Andrew,Gavin,Georgiana,Chan,Dan,Veronica,Clara,Robert,Valerie,Gregor
Andrew,NaN,8.00,8.0,4.00,7.5,8.5,2.50,4.0,4.00,6.00
Gavin,8.0,NaN,9.0,14.00,5.0,4.0,5.75,5.0,5.50,6.00
Georgiana,8.0,9.00,NaN,4.50,9.0,3.5,3.00,2.5,5.00,9.50
Chan,4.0,14.00,4.5,NaN,14.0,6.5,1.75,1.0,4.00,12.00
Dan,7.5,5.00,9.0,14.00,NaN,4.0,4.00,5.0,4.50,5.00
Veronica,8.5,4.00,3.5,6.50,4.0,NaN,4.50,5.0,2.00,4.00
Clara,2.5,5.75,3.0,1.75,4.0,4.5,NaN,7.5,0.75,0.75
Robert,4.0,5.00,2.5,1.00,5.0,5.0,7.50,NaN,3.00,4.00
Valerie,4.0,5.50,5.0,4.00,4.5,2.0,0.75,3.0,NaN,7.50
Gregor,6.0,6.00,9.5,12.00,5.0,4.0,0.75,4.0,7.50,NaN

Let's focus on getting some recommendations for Valerie. To do this we need to pick a customer that is similar. Reading off the table above you can probably see that Veronica is closest in her tastes to Clara, but we can do this in python using the "sort_values()" function:

In [16]:
user_distances.loc["Valerie"].sort_values()

Clara        0.75
Veronica     2.00
Robert       3.00
Andrew       4.00
Chan         4.00
Dan          4.50
Georgiana    5.00
Gavin        5.50
Gregor       7.50
Valerie       NaN
Name: Valerie, dtype: float64

To make some recommendations to Valerie we need to know what Clara likes. We do this as follows:

In [17]:
#-- sort valeries distances, and keep the closest one
closest = user_distances.loc["Valerie"].sort_values()[:1]

#-- extract Clara's scores from our original data
closest_scores = data.loc[closest.index]
closest_scores

,Tame Impala,Broken Bells,Adele,Radiohead,Tenacious D,The Strokes,Skrillex,Vampire Weekend,Jay-Z
Clara,4.75,NaN,4.5,5.0,NaN,4.25,NaN,NaN,4.0

### Task 1f: Making a recommendation
Given this data, what would you recommend? Well, we aren't going to recommend something that Valerie has already bought - rather we look where she has a "NaN" and find which of those Clara (someone with similar tastes) votes highly. Here is Valerie's data together with Clara's to help you pick:

In [18]:
 data.loc[["Valerie", "Clara"]]

,Tame Impala,Broken Bells,Adele,Radiohead,Tenacious D,The Strokes,Skrillex,Vampire Weekend,Jay-Z
Valerie,NaN,4.0,4.0,NaN,NaN,4.00,1.0,1.0,NaN
Clara,4.75,NaN,4.5,5.0,NaN,4.25,NaN,NaN,4.0

I picked "Radiohead" - Valerie hasn't bought any of their music, and Clara though they were great. So either via a direct mail, or a message on a till receipt, or an offer voucher the business can now leverage this information to try and make a sale!

Note however, this is a very limited viewpoint - maybe it was a quirk that Clara liked "Radiohead". Perhaps we should have used a bigger 'neighbourhood' and found a few more people who were simlar to Valerie and merged their results?

In [19]:
#-- sort Valerie's distances, and keep the closest three this time!
closest = user_distances.loc["Valerie"].sort_values()[:3]


#-- extract the scores for these 3 people from our original data
closest_scores = data.loc[closest.index]
closest_scores

,Tame Impala,Broken Bells,Adele,Radiohead,Tenacious D,The Strokes,Skrillex,Vampire Weekend,Jay-Z
Clara,4.75,NaN,4.5,5.0,NaN,4.25,NaN,NaN,4.0
Veronica,3.00,NaN,5.0,4.0,2.5,3.00,NaN,NaN,NaN
Robert,4.00,NaN,3.0,5.0,NaN,2.00,NaN,NaN,1.0

This time we want to take the mean of all these similar people's ratings, as this will give us a smoothed picture of what Valerie might like:

In [20]:
recommendations = np.mean(closest_scores)
recommendations

np.float64(3.6666666666666665)

Let's put these predictions for what Valerie will like in descending order, and get rid of the bands for which no one had made any purchases (and which hence had an NaN).

In [21]:
# recommendations = recommendations.sort_values(ascending=False).dropna()
recommendations = closest_scores.mean().sort_values(ascending=False).dropna()
print(recommendations)

Radiohead      4.666667
Adele          4.166667
Tame Impala    3.916667
The Strokes    3.083333
Tenacious D    2.500000
Jay-Z          2.500000
dtype: float64

One final step remains: to see which of these Valerie hasn't bought before. This time let's automate the process to drop out our final recommendations.

In [22]:
# loop around every band
for r in recommendations.index:

    #-- check if Valerie has never bought and rated this band's music before
    if data.loc["Valerie"][r] >= 0:

        #-- and if so, remove it from our recommendations
        recommendations = recommendations.drop(r)

#-- leaving us with our final results in order of what we'd recommend
print(recommendations)

Radiohead      4.666667
Tame Impala    3.916667
Tenacious D    2.500000
Jay-Z          2.500000
dtype: float64

We still recommend "Radiohead" but are less confident this time. Maybe we should also see if Valerie would like to give Tame Impala a try (as should you!).

### Task 1g: The sparsity problem - Cosine Similarity to the rescue
Remember we noted that our similarity measures were very dependent on how many items two people had in common - more so in fact than what they rated those items. Time to fix this with cosine similarity, which you should recall from the Week 4 lecture slides.

The rows in our tables are essentially vectors, and we can measure the angle between two vectors to see how similar they are. Crucially this calculation - the cosine similarity - is **not** dependent on the **number** of items two people have in common, and so is preferable when we have sparse datasets. This tends to be the case in two scenarios - text and consumer purchases - so exactly what we need here.

Find below a replacement function for the one we created for manhattan distance:

In [23]:
def cosine_distance(user1, user2):
    dot_product = np.sum(user1 * user2)
    norm1 = np.sqrt(np.sum(np.square(user1)))
    norm2 = np.sqrt(np.sum(np.square(user2)))
    return dot_product / (norm1 * norm2)

<span style="font-weight:bold; color:green;">&rarr; Recalculate the user distances table this time using this function for cosine similarity (and referring to the code in task 1d)</span>

In [24]:
#-- generate new user_distances using cosine_distance rather than manhattan distance
new_user_distances = {}

#-- loop through all of the customers
for i in data.index:
    distances = {}
    for j in data.index:
        #-- if they are different people calculate and store their distance
        if i != j:
            distances[j] = cosine_distance(data.loc[i],data.loc[j])
        #-- otherwise just add a "not-a-number" in the results table
        else:
            distances[j] = np.nan
    new_user_distances[i] = distances
    
    

#-- cast the results as a pandas dataframe
new_user_distances = pandas.DataFrame.from_dict(new_user_distances, orient="index")
new_user_distances

,Andrew,Gavin,Georgiana,Chan,Dan,Veronica,Clara,Robert,Valerie,Gregor
Andrew,NaN,0.530192,0.894823,0.809470,0.766622,0.910446,0.811215,0.846217,0.554700,0.724899
Gavin,0.530192,NaN,0.540393,0.519197,0.891961,0.371413,0.254781,0.320079,0.391652,0.778800
Georgiana,0.894823,0.540393,NaN,0.878426,0.648736,0.924628,0.835004,0.901303,0.624716,0.802569
Chan,0.809470,0.519197,0.878426,NaN,0.561768,0.825417,0.783267,0.924733,0.305329,0.571946
Dan,0.766622,0.891961,0.648736,0.561768,NaN,0.563517,0.471370,0.485479,0.560093,0.832577
Veronica,0.910446,0.371413,0.924628,0.825417,0.563517,NaN,0.852434,0.884717,0.560241,0.717939
Clara,0.811215,0.254781,0.835004,0.783267,0.471370,0.852434,NaN,0.935153,0.490399,0.543001
Robert,0.846217,0.320079,0.901303,0.924733,0.485479,0.884717,0.935153,NaN,0.381385,0.549965
Valerie,0.554700,0.391652,0.624716,0.305329,0.560093,0.560241,0.490399,0.381385,NaN,0.745044
Gregor,0.724899,0.778800,0.802569,0.571946,0.832577,0.717939,0.543001,0.549965,0.745044,NaN

<span style="font-weight:bold; color:green;">&rarr; Recalculate your recommendations for Valerie based on our new table</span>

In [25]:
#-- sort valeries distances, and keep the closest three
new_closest = new_user_distances.loc["Valerie"].sort_values()[:3]

#-- extract the scores for these 3 people from our original data
new_closest_scores = data.loc[new_closest.index]
new_closest_scores

,Tame Impala,Broken Bells,Adele,Radiohead,Tenacious D,The Strokes,Skrillex,Vampire Weekend,Jay-Z
Chan,5.0,1.0,3.0,5.0,1.0,NaN,1.0,NaN,NaN
Robert,4.0,NaN,3.0,5.0,NaN,2.0,NaN,NaN,1.0
Gavin,2.0,3.5,NaN,2.0,3.5,NaN,4.0,3.0,NaN

You should have found that now Chan, Robert and Gavin are the three closest customers to Valerie - this is a dramatic difference from before. Let's see what the consequences are for recommendations:

In [26]:
recommendations = new_closest_scores.mean().sort_values(ascending=False).dropna()
print(recommendations)

Radiohead          4.000000
Tame Impala        3.666667
Adele              3.000000
Vampire Weekend    3.000000
Skrillex           2.500000
Broken Bells       2.250000
Tenacious D        2.250000
The Strokes        2.000000
Jay-Z              1.000000
dtype: float64

However, we still get Radiohead as the winner, but Vampire Weekend have increased up the ranks and pipped Adele in our list.

## Conclusions

Recommendation systems of this nature underpin an increasing amount of targeted marketing systems. There are many forms of variants of collaborative filtering of this nature - it is a huge and growing area of business research.

There are also a couple of other popular distance measures - one example is the use of **"Pearson correlation"** to compare between two people's ratings as this accounts for different tendencies in rating styles that people might have (some people may always rate highly in comparison to others, so while they appear far apart, their correlation will actually be close). However, this still suffers from favouring people with more items to compare, so in most business domains cosine-similarity is preferred.

#### Final Question:
If your original table had contained not user ratings, but for each person how many times they listened to music by a particular artist (e.g. the number of listens on spotify) which distance measure would you prefer and why?
* Absolute distance
* Euclidean distance
* Cosine similarity
* Pearson correlation

#### Final task:
Update your analysis to test this out! To do this take a cross-validation approach, building a model recommender 10 times, but each time leaving one person out to test on. For that test person randomly pick one of their ratings, make it unknown, project them into your model and see what the model predicts for that blanked rating. Then sum the accuracy over all tests.

In [27]:
import numpy as np
import pandas as pd

# data is your existing user-item table from earlier cells
# rows: users, columns: artists, values: ratings or listen counts, missing as NaN

rng = np.random.default_rng(42)

def similarity(u, v, metric="cosine"):
    mask = u.notna() & v.notna()
    if mask.sum() == 0:
        return np.nan

    a = u[mask].astype(float).to_numpy()
    b = v[mask].astype(float).to_numpy()

    if metric == "cosine":
        denom = np.linalg.norm(a) * np.linalg.norm(b)
        return np.dot(a, b) / denom if denom != 0 else np.nan

    if metric == "pearson":
        if len(a) < 2:
            return np.nan
        if np.std(a) == 0 or np.std(b) == 0:
            return np.nan
        return np.corrcoef(a, b)[0, 1]

    if metric == "manhattan":
        dist = np.sum(np.abs(a - b))
        return 1.0 / (1.0 + dist)  # convert distance to similarity

    if metric == "euclidean":
        dist = np.sqrt(np.sum((a - b) ** 2))
        return 1.0 / (1.0 + dist)  # convert distance to similarity

    raise ValueError("Unknown metric")

def predict_one(test_user_vector, train_df, target_item, metric="cosine", k=3):
    sims = []
    vals = []

    for other_user in train_df.index:
        v = train_df.loc[other_user]
        if pd.isna(v[target_item]):
            continue

        s = similarity(test_user_vector, v, metric=metric)
        if pd.isna(s):
            continue

        sims.append(s)
        vals.append(float(v[target_item]))

    if len(sims) == 0:
        item_mean = train_df[target_item].mean()
        if not pd.isna(item_mean):
            return float(item_mean)
        user_mean = test_user_vector.mean()
        if not pd.isna(user_mean):
            return float(user_mean)
        return float(train_df.stack().mean())

    sims = np.array(sims)
    vals = np.array(vals)

    # top-k neighbors by similarity
    top_idx = np.argsort(sims)[::-1][:k]
    sims = sims[top_idx]
    vals = vals[top_idx]

    denom = np.sum(np.abs(sims))
    if denom == 0:
        return float(np.mean(vals))

    return float(np.dot(sims, vals) / denom)

def cross_validate_leave_one_user_out(df, metric="cosine", k=3, seed=42):
    rng_local = np.random.default_rng(seed)
    tests = []

    for user in df.index:
        row = df.loc[user]
        observed = row.dropna().index.tolist()
        if len(observed) == 0:
            continue

        # hide one known value for this user
        hidden_item = rng_local.choice(observed)
        true_value = float(row[hidden_item])

        test_user = row.copy()
        test_user[hidden_item] = np.nan

        train = df.drop(index=user)
        pred = predict_one(test_user, train, hidden_item, metric=metric, k=k)

        err = abs(pred - true_value)
        rounded_hit = int(round(pred) == round(true_value))

        tests.append({
            "user": user,
            "item": hidden_item,
            "true": true_value,
            "pred": pred,
            "abs_error": err,
            "rounded_hit": rounded_hit
        })

    res = pd.DataFrame(tests)

    summary = {
        "metric": metric,
        "n_tests": len(res),
        "sum_accuracy_hits": int(res["rounded_hit"].sum()),   # requested summed accuracy
        "hit_rate": float(res["rounded_hit"].mean()) if len(res) else np.nan,
        "sum_abs_error": float(res["abs_error"].sum()) if len(res) else np.nan,
        "mae": float(res["abs_error"].mean()) if len(res) else np.nan,
        "rmse": float(np.sqrt(np.mean((res["pred"] - res["true"])**2))) if len(res) else np.nan
    }

    return res, summary

# If you truly have listen counts, this transform usually helps:
# df_model = np.log1p(data)
# For current ratings table, use data directly:
df_model = data.copy()

all_summaries = []
all_results = {}

for m in ["manhattan", "euclidean", "cosine", "pearson"]:
    res, summ = cross_validate_leave_one_user_out(df_model, metric=m, k=3, seed=42)
    all_results[m] = res
    all_summaries.append(summ)

comparison = pd.DataFrame(all_summaries).sort_values("mae")
print(comparison)

# Show detailed test rows for the best metric
best_metric = comparison.iloc[0]["metric"]
print("\nBest metric:", best_metric)
print(all_results[best_metric])

      metric  n_tests  sum_accuracy_hits  hit_rate  sum_abs_error       mae  \
1  euclidean       10                  1       0.1       9.807315  0.980732
0  manhattan       10                  3       0.3      10.732391  1.073239
2     cosine       10                  1       0.1      10.776072  1.077607
3    pearson       10                  0       0.0      16.266315  1.626632

       rmse
1  1.079745
0  1.202124
2  1.210257
3  1.914870

Best metric: euclidean
        user          item  true      pred  abs_error  rounded_hit
0     Andrew   Tame Impala  5.00  4.037565   0.962435            0
1      Gavin      Skrillex  4.00  3.069184   0.930816            0
2  Georgiana   Tenacious D  1.50  2.524091   1.024091            0
3       Chan         Adele  3.00  4.044994   1.044994            0
4        Dan   Tenacious D  4.50  3.343982   1.156018            0
5   Veronica   The Strokes  3.00  3.587711   0.587711            0
6      Clara   Tame Impala  4.75  4.348708   0.401292            0
7     Robert   The Strokes  2.00  3.941518   1.941518            0
8    Valerie         Adele  4.00  4.346939   0.346939            1
9     Gregor  Broken Bells  4.50  3.088498   1.411502            0